name: jekyll test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Jekyll
      run: |
        # sudo apt-get update  
        sudo apt-get install --assume-yes ruby-full build-essential zlib1g-dev liblzma-dev git < /dev/null  
        mkdir ~/.ruby
        export GEM_HOME=~/.ruby/
        export PATH="$PATH:~/.ruby/bin"
        gem install -v "2.2.4" bundler 
        bundle update github-pages 
        bundle install --without development test 
        bundle exec jekyll build --config _config.yml,_config-root.yml
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test for broken links
      run: python checklinks.py
